/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as LeaguesIdRouteImport } from './routes/leagues.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIdRoute = LeaguesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeaguesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leagues'
    | '/matches'
    | '/profile'
    | '/leagues/$id'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/leagues'
    | '/matches'
    | '/profile'
    | '/leagues/$id'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/leagues'
    | '/matches'
    | '/profile'
    | '/leagues/$id'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$id': {
      id: '/leagues/$id'
      path: '/$id'
      fullPath: '/leagues/$id'
      preLoaderRoute: typeof LeaguesIdRouteImport
      parentRoute: typeof LeaguesRoute
    }
  }
}

interface LeaguesRouteChildren {
  LeaguesIdRoute: typeof LeaguesIdRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesIdRoute: LeaguesIdRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
